language: python
python:
- '3.5'
- '3.6'
- nightly
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
before_install:
- pip install coverage coveralls
install:
- pip install .
script:
- pip install .[test]
- coverage run --source=usp setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: mediacloud-travis
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  password:
    secure: d2oQd9ojE8K50uGgjuisonPGEC4NLGVHbAx/IFDCC3K5/oVDeNG7BuIqQdNS0ObFJWH8yjHDcjoq1J1RvRhJlNNWYercm5qN+3ANMePINBt7iCgzcoSA8/MyyKvlId/8VqEnbU1ZD4ou3QBfG5y2AXzrGZSS3qJ7TlT5mt8N31bDAdB2CsR3bRcVjtylu8zPuFarhpnn0X7y/T/jOWhVuO8OI2kd2P+3h9zR88nJVv8xThsCclwHqZns48yDmOHKpAjuSAeexUdnbLNPadSS3ial79WGcnjsnfb5vNTrp3H9dhQLoIJbCXjemwgWiGadOee0HQJDZvdNPJzojw6QXiXASORmVhLV3I1IKa0g+m2HPcGqBKWMloAvVQEd4d9SKH6/lf0unSIOb1UAeMASPsZTw//60pBH8L7SmcwtskJNfAr2RnUDK7P6C/vkwEYiET44DCPzRGzcoaQfp/Cybh9tSxbHpdqkCkW59VeVFA0dWgSrVfywwDbFACky0gHK/YEQK45dzRrUxKTBcYBD3RH2iIjZsMEesTSfjZ9ePT3gUdA4sqsYRASGq8nEqFWY32dqr/4JQulzFffdVQcbnrk/gxk1mRFIjboyx6c0vJaroO+tsNRQSlnMa8PbH6BE02YIRFgHPauLx8XZpOruXYCap6Mr8w6VvWjYH8M41uk=

