language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - pip install coverage coveralls
install:
  - pip install .
script:
  - pip install .[test]
  - coverage run --source=usp setup.py test
after_success:
  - coveralls

