language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
before_install:
  - pip install coverage coveralls
install:
  - pip install .
script:
  - pip install .[test]
  - coverage run --source=usp --verbose setup.py test
after_success:
  - coveralls

